
# A few comments on computing {#computing}

_Contributors: Ben Arnold_

Like all of our data science workflows, generating a random sequence needs to be transparent and reproducible. See Proctor's handbook on data science. The principles we describe there are germane for randomization sequences as well!

https://proctor-ucsf.github.io/dcc-handbook/intro.html

All of the examples in this guide use R software. There are surely many other effective ways to generate sequences in other software, but R includes many convenient functions for pseudo-random number generation.

Our advice for generating the sequence is to not rely on any packages beyond base `R`.  The R language and packages evolve rapidly. Using base R ensures that functions will behave consistently over time.  For example, many tidyverse packages such as the [`dplyr`](https://dplyr.tidyverse.org/) package are incredible for data manipulation. [`dplyr`](https://dplyr.tidyverse.org/) includes many convenient pseudo-random sampling routines, but as of this writing its syntax rapidly evolves -- some commonly used functions seem to be replaced or deprecated every few months. This makes the code more fragile.  As an exception, we do use [`ggplot2`](https://ggplot2.tidyverse.org/) for graphics in randomization diagnostics examples below.

