
# Creating a Randomization Directory {#directory}

_Contributors: Ben Arnold_


The files used to generate a randomization sequence should live in one directory. They should be clearly labeled. They should include lots of comments and documentation to orient a new reader to their contents. The directory should include, at minimum:

| Item  | |
:----:|:--------------------|
____ 1. |  A metadata README file that describes all files in the directory. |
____ 2. |  The script that generates the randomization sequence(s). | 
____ 3. |  Randomization diagnostics (typically an output file from the script). | 
____ 4. |  The randomization sequence(s) generated, stored as `.csv` files. | 
____ 5. |  The key that maps group labels to masked codes (masked trials only) | 
____ 6. |  A list of team members with access to the masked codes (masked trials only) and randomization sequence file(s) |

Table: (\#tab:dirchecklist) Checklist of items that should be in the Randomization Directory


For unmasked randomization, we recommend creating a subdirectory within a trial's parent directory called `Randomization`.  In the hypothetical `MyTrial` study below, create a new subdirectory nested within:

> `~/Box Sync/MyTrial/Randomization`

If the randomization sequence is masked, then we need to keep the randomization files separate from the main trial directory. Otherwise team members who should not know the mapping between treatment labels and masking codes could discover the link. The sequence could also be discoverable, and if a team member is involved in treating patients that could bias the allocation.

In masked trials, we recommend creating a parallel, shadow directory for the trial with restricted access permissions. We typically use the suffix `-unmasked-materials` to identify the restricted access directories. They should live on the same encrypted server as the trial's main directory, e.g.:

> `~/Box Sync/MyTrial-unmasked-materials/Randomization`

Note that an `-unmasked-materials` directory can contain other, sensitive, restricted access materials. Such as: interim analyses requested by the trial's Data and Safety Monitoring Committee, and the primary analysis files/results up until the trial is unmasked.

We recommend the `-unmasked-materials` directory reside on a secure, cloud server that meets UCSF's IT security standards.  At this time, that includes Box and Microsoft OneDrive. The trial's biostatistician should "own" the directory and should carefully control team member access. Restrict permissions/access to only team members who should have access (item #6, above).  Do not create a shareable link to the directory or individual files within the directory.

If the randomization script is developed on GitHub, then the trial should maintain a secure repostitory that includes unmasked materials and is highly restricted.  Additional details in the chapter on [Masking](#masking).


 | Key Points |
:----:|:--------------------|
1     | The trial's biostatistician should control access to a trial's directory of unmasked materials |
2     | At least 3 team members should have access to unmasked materials at all times |

Table: (\#tab:unmaskeddir) Key Points for Restricted Access Directories in Masked Trials

